perform yalla script version comparaison

diff --git a/create-project b/create-project
--- a/create-project
+++ b/create-project
@@ -2,6 +2,7 @@
 
 # Exit immediately on error
 set -e
+trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
 
 ##
 ## This script creates the necessary directories and files
@@ -11,14 +12,24 @@ set -e
 # Load common vars and functions
 . "$(pwd)/yalla/src/lib/common.sh"
 
-_yalla_settings
-
-exit
-
 
 if ! [ -x "$(command -v yalla)" ]; then
     _install_yalla_bin
 fi
+
+
+_h1 "Check yalla scripts update"
+_yalla_check_update
+
+# if [ "$local_version" -lt "$remote_version" ]
+#   then
+#     echo "version mismatch"
+#   else
+#     echo "qsdqs"
+# fi
+exit
+#_line
+#_h1 "Init new yalla project"
 
 
 for folder in "${FOLDERS[@]}"
@@ -55,3 +66,4 @@ Options:
   -h --help  Display this help information.
 HEREDOC
 
+_yalla_settings
