Unable to solve passing args from main to mysql devilbox

diff --git a/src/actions/devilbox b/src/actions/devilbox
--- a/src/actions/devilbox
+++ b/src/actions/devilbox
@@ -1,4 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# Exit immediately on error
+set -e
+trap 'echo "Aborting due to errexit on line $LINENO. file $(cd $(dirname "$0"); pwd)/$(basename "$0"). Exit code: $?" >&2' ERR
+
 
 # Load params & export local configuration
 set -o allexport
@@ -64,7 +69,6 @@ case "$ACTION" in
     # @see https://github.com/docker/compose/issues/3352
     # ------ / unsed
     mysql)
-        shift
         $docker_exec "cd ${CWD}/${CURRENT_DIR_NAME}/; ./yalla/src/lib/devilbox.cmd.mysql.sh $(_args_list "$@")"
         ;;
     install)
